services:
  book_catalog:
    image: book_catalog_image
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgresql://task3db_user:TIvl0maLWmIkSItDX61dwXNn5KdGV5Ld@dpg-cregf9jv2p9s73cv1ju0-a.singapore-postgres.render.com/task3db
    restart: 'no'

  inventory_management:
    image: inventory_management_image
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
      - '8001:8001'
    environment:
      - DATABASE_URL=postgresql://task3db_user:TIvl0maLWmIkSItDX61dwXNn5KdGV5Ld@dpg-cregf9jv2p9s73cv1ju0-a.singapore-postgres.render.com/task3db
    restart: 'no'
